### PR TITLE
Feat 14 Gradle

### LINKED ISSUE #14: Run gradle in directory

### PR DESCRIPTION
**Pull request by jsjolen**
I have implemented Gradle communications but it's hard to test (need to set up an environment to test it in, etc.). I tried out mocking but it would've required a massive amount of work so I'm avoiding that. I then tried testing by using our project, but this obviously leads to looping when running gradle test :-).

I'll be looking into testing this tomorrow.

Fixes #14

### CODE REVIEW

**Comment by modnikhil** [comment]
Overall, source code looks good. Waiting for some sort of test cases to merge. 

Toyed around with the test in this branch locally. Is the main problem stemming from the fact that the test case runs `gradle build` which runs the test cases causing an infinite loop? If so, is it possible to build while excluding the test cases for `GradleComm.java`?

**Comment by jsjolen** [comment]
That's exactly it! Also, probably not. I'm not sure which way works best.

**Comment by jsjolen** [comment]
Actually you could do something like make a file and check if the file exists or something like that. I'll look into it!

**Comment by jsjolen** [comment]
Aaah!
@modnikhil I'm sorry, for some reason I clicked merge (I can't even remember doing that, I must have clicked the wrong button). I'll be fixing up a new issue for the tests specifically and write code for it.

**Pull request merged**
