### PR TITLE
feat 18: GitHub status

### PR DESCRIPTION
**Pull request by seven2four83**
Base files. No test cases as it's the basic model. Will create test cases as functionality gets added

### CODE REVIEW

**Comment by jsjolen** [comment]
I don't think you need to import that swing package :).

**Comment by jsjolen** [comment]
So is this what will make a status on the corresponding pull request regarding the build failing, succeeding, etc?

**Comment by seven2four83** [comment]
> So is this what will make a status on the corresponding pull request regarding the build failing, succeeding, etc?

Yes. It is.

**Comment by jsjolen** [comment]
OK, sounds good. I'm merging this.

**Pull request merged**
